:toc:
:experimental:

== Message Command Interpreter [[message-command-interpreter]]

The Message Command Interpreter (MCI) allows you to do a variety of things within messages you type.
Each MCI command consists of:

* the British pound character (£) for Commodore users, or backslash (\)
for other computers
* a command letter (can be either upper- or lowercase)
* a number or letter
* any arguments/parameters.

Numbers must be entered in a certain way.
Since the parameter after a command letter may only be one character, letters are substituted in some cases, as follows:

.MCI numbering system
[%autowidth]
[%header]
|===
| Num | Equals | Num | Equals
| ``1`` |``1`` or ``A`` |``9`` |``9`` or ``I``
| ``2`` |``2`` or ``B`` |``10`` |``J``
| ``3`` |``3`` or ``C`` |``11`` |``K``
| ``4`` |``4`` or ``D`` |``12`` |``L``
| ``5`` |``5`` or ``E`` |``13`` |``M``
| ``6`` |``6`` or ``F`` |``14`` |``N``
| ``7`` |``7`` or ``G`` |``15`` |``O``
| ``8`` |``8`` or ``H`` | |
|===

====
TIP: Think of it as "`extended hexadecimal.`"
And by the way, this next good-sized chunk was pretty extensively reworked; I think the examples in the original manual don't always explain themselves very well.

TIP: If ever you need to output a British pound sign, type two of them.
This is technically called "`escaping`" MCI; the first prepares to interpret the following character as an MCI command, the second cancels it.
====

// Include MCI reference here

In general, MCI is what "`spices up`" an Image BBS.
It allows you to add color, cursor movement, and a "`personal touch`" to your BBS and messages.
The MCI commands available in Image BBS are:

### `£AnTEXT£` About

Compare MCI variable £Vn to TEXT.
Notice the ending pound sign which delimits the comparison.
(For a list of MCI variables, see the £V command.)
The comparison result can be used with £D or £T.

_£A2SYSOP£_ Compares the user's handle (`£V2`) to _SYSOP_.

### `£Bx` Bells

Send _x_ bell characters [CHR$(7)] to the user; if the user's terminal supports bells, they hear them.

====
TIP: Speed up or slow down by using the £Sx command!
====

### `£Cx` Color

Set the current display color to _x_, where _x_ is from the following table:

[cols=",,,,,",]
|===
|_a/1_ |_white_ |_f/6_ |_dark blue_ |_k_ |_dark grayfootnote:[ in ANSI
graphics or Commodore 128 80-column mode: £C8: dark purple, £CK: dark
cyan] (+)_

|_b/2_ |_red_ |_g/7_ |_yellow_ |_l_ |_medium gray_

|_c/3_ |_cyan_ |_h/8_ |_orange (+)_ |_m_ |_light green_

|_d/4_ |_purple_ |_i/9_ |_brown_ |_n_ |_light blue_

|_e/5_ |_dark green_ |_j_ |_light red_ |_o_ |_light gray_
|===

Table 21: MCI color codes

* 0, black, is omitted since that is usually the color choice for terminal backgrounds.
* Commodore users can use _CTRL_- or _C=_ _1-8_ instead of _£Cx_.

£Dx Jump if not equal

Skips _x_ lines when the result of the last compare command (£A or £T) was _not_ equal.

___Display an appropriate message based on whether the user's handle is
or is not __SYSOP_:__

__£A2SYSOP££D1 __Compare user's handle to SYSOP, skip next line if not

__Hello, Sysop!£D1 __Output "`Hello, Sysop!`", skip next line

_Hey, you can't read this! _Output message, continue__

_£X1 _Abort the file or message__

£Ex Jump if equal

Skip _x_ lines if the result of the last compare command (£A or £T) _was_ equal.

Display a message based on whether the user's handle is USER:

_£A2USER££E1_

_Congratulations, your handle is USER!£E1_

_Too bad your handle isn't USER!_

_£X1 _Abort the file or message__

£F1 Form feed

This command sends a "`clear screen`" character to the user. [CHR$(147) on Commodore equipment, or CHR$(12)--a form feed -- in ASCII mode].

£Gx Get character

Wait until the user presses a key.  The keypress is stored in an$ (MCI variable £v7).

If x=1, only uppercase input is allowed. If x=0, both uppercase and lowercase are allowed.

__Press a key: £G1 __Prompts the user and waits for one

keypress (only uppercase input is accepted).

£Hx Backspaces

Display _x_ backspaces/deletes (depending on the user's terminal requirements).

_Apple£H5Banana_ This displays Apple, immediately erases it with five

backspace/delete characters, then Banana

is displayed in its place.

£Ix Line input

Pauses output, allowing the user to input a line of text. The input is stored in AN$ (MCI variable £V7).

* If x=0, the input can be in both upper- and lowercase.
* If x=1, the input is in uppercase only.

__Enter your name: £I1 __Prompts the user, then accepts input

in all uppercase characters.

_Hello, £V7!_ Echo the user's input.

==

=== £Jx Jump

Do not display the next x lines of the message or file.

_Displayed£J1_ This skips the next line.

_Not displayed_

_Displayed again_

£Kx Kolorific mode

Changes the color of each character output.

* If x=0 (zero), Kolorific mode is turned off.
* If x is any other color code (see £Cx), Kolorific mode is enabled, starting with £Cx.

_£K2This is a test£K0_ Turn Kolorific mode on, starting with the color red.

Displays `This is a test,` then turns Kolorific mode off.

£Lx Printer

Control the printer attached to the BBS, if online.

* If x=0, printed output is stopped.
* If x=1, printed output is started (or resumed).

_Note:_ Printed output stops at the end of each line; you must include £L1 on each line to be printed.

_£LlHello_ Print _Hello_ on the printer.

£Nx New line

Display _x_ carriage returns.

£Ox "Over"

This command repeats a character 19 times.  It is useful for making menus, etc.

Parameters: Replace x with the character wanted.

*£0-£0-*

Displays the following:

_*--------------------------------------*_

£Px Print mode [[mci-print-modes]]

Sometimes referred to as "`cursor dancing,`" print modes allow each character output to be displayed in a variety of ways, usually to move the cursor, or perform "`special effects.`"
Replace _x_ with the print mode number.  The print mode is set back to 0 at the end of each line.

====
There are thirteen very powerful print modes in Image BBS.  We suggest
trying to come up with interesting ways to use them--it is possible to
create an entire "`movie`" file entirely within the Image BBS editor with
these commands!
====

__ASCII:__

0 - normal printing

1 - character, backspace, character

2 - character, 8 spaces, 8 backspaces

3 - character, backspace

4 - space, character, 2 backspaces, character

5 - character, bell

__COMMODORE C/G:__

_==============_

6 - character, 2 cursor lefts (displays !drawkcab)

7 - character, cursor left, cursor up (displays up)

8 - character, cursor left, cursor down (displays down)

(fixme: add the rest, 4 diagonals)

£Qx Reset MCI defaults

Turns off the following features:

* Printer mode (see £Lx)

* Reverse mode (see £Rx)

* Uppercase mode (see £Ux)

The current print mode (see £Px) and print speed (see £Sx) are set to 0 for normal output at the fastest speed.

Parameters: * If x=0, then the current color is set to the default color.

* Otherwise, the default color and current color is set to x.

(fixme)

£Rx Reverse mode

Controls displaying text in normal or reverse modes.

Parameters:

* If x=0, reverse mode is turned off

* If x=1, reverse mode is turned on

Notes:

* Reverse mode turns off at the end of every line.

* Commodore users can also use CTRL-9 / CTRL-0.

£Sx Print speed

Delay character output by a multiple of tenths of a second.

Parameters: * x ranges from 1-J (.1 to 1 second)

£TxTEXT£ Test variables

Used in conjunction with £D and £E.  Compares a variable to TEXT (similar to £A).

If x=1, tests user input (AN$).

If x=2, tests access group (AC%).

£T29££D1 Compare the user's access level to 9;

Hi, sysop! Welcome!£X1 display an appropriate message.

£V2, this function is only for sysops.

£Vx MCI variables

Display the desired MCI variable.

Parameters: x is MCI variable number:

.MCI variables
[cols=",,,",]
|===
|_0 d1$_ |Current date/time |_8 d2$_ |Board name at entry
|_1 ld$_ |Last call date |_9 d3$_ |Last user on BBS
|_2 na$_ |User's handle |_j ak$_ |Space, _LL%_-2 character line, CR
|_3 rn$_ |User's real name |_k d5$_ |True last call date
|_4 ph$_ |User's phone number |_l d4$_ |Current ML protocol
|_5 bn$_ |Name of BBS |_m ag$_ |Access group name
|_6 b$_ |System variable |_n cc$_ |Two-character login identifier
|_7 an$_ |Last user input |_o dd$_ |Login identifier + user ID
|===

£Wx Wait

Delay x seconds before proceeding, similar to £Sx.

Parameters: * x ranges from 1-J (1 to 15 seconds)

£X1 ........................................... Abort file

Skips the rest of the lines in a file/message, not displaying anything contained in those lines.

{empty}[The number of lines skipped is actually limited to 255; I discovered this while re-writing the BBS editor help menu file.]

x .................................... Leading characters

When you use £%v (below), this specifies either:

* The number of digits to display

* To use leading zeroes or spaces

Parameters: * When x is a number [#FIXME# between 1 and 5?], x sets the number of digits to display a numeric value with.

* When x equals zero, as many digits are in the number are displayed.

* When x is a space character, leading spaces are used, but the number of digits to display is not affected.

See the examples for £%v, below.

=== £%v .............................. Display integer variable

Display the value of any one-letter integer variable with or without leading characters.

{empty}[The periods in the examples are not shown in actual use of this command; they only illustrate how many leading spaces are used.]

Example 1: _£#4£# £%a_ If a%=l,   this displays "...1"

Example 2: _£#2£%a_ If a%=l,   this displays "01"

If a%=23,  this displays "23"

If a%=789, this displays "89", the _rightmost_ two digits.

.Example 3

`£#0£%a`

If a%=l, this displays `1`

If a%=42, this displays `42`

=== `£$x` Display string variable

Display any one-letter string variable (A$, for example).

£$a

Display the contents of the string variable A$.

=== `£←xx` Tab

This command moves the cursor from the left column to column `#_xx_`.

To tab over less than ten columns, use a leading zero (_e.g._, `£←05`, `£←08`).

NOTE: The kbd:[←] is to the left of the kbd:[1] key.

====
NOTE: If the tab-to column specified is less than the column where the cursor is now, any text after the tab command is displayed directly at the cursor position.
====
