:experimental:
== `+.reledit`

====
This documentation was modified slightly from the text files on the RELedit and Networking plus-file disks.
I in no way take credit for the original documentation, just the cleanup and integration into these more current, streamlined documentation.
====

RELedit is a program which eases the setup and administration of message and file transfer bases.
Just run `+.reledit` from the main prompt.

After a short delay as RELedit reads the system configuration, you see the main menu.
Across the top is the title of the program and a copyright message.
Below that is data on your BBS that includes the number of Subs, U/Ds, etc. that are defined, as well as your node number if you are on the network.
Below that are 5 options:

```
S – Sub
U - U/D
X - U/X
G - SIG
N - NetSubs
```

Select S, U, X, G or N.

====
NOTE: If you are not part of a network, the NetSubs option will not appear.
This documentation assumes you are networked.
If not, operation is exactly the same, you just can't use the NetSub option.
====

=== Editing Sub-Boards [[editing-sub-boards]]

If you select S, the BBS enters the Sub-board list editor's first screen.
It consists of a listing of the Subs (if any) you have defined.

The list of Subs show:

* The title
* Type
* Whether it is open or closed
* The device and drive the messages are saved to
* The ID number of the SubOp (ID# 0 means no SubOp)
* The password (if any)
* The access level required to see/enter it
* If it is a NetSub, #a small n will appear after the access level#.

To add a Sub, type kbd:[A] and hit kbd:[Return].

==== Ranges

Typing ranges of sub-boards to add, delete, move, or insert works similar to BASIC's `list` command.

[%autowidth]
[%header="no"]
|===
|kbd:[L] |To list all the Subs.

|kbd:[L3] |Optionally, follow that by a number to start listing the Subs at.

|kbd:[L3-] |You can follow this with a comma or dash to list from this number to the end of the list.

|kbd:[L3-19] |You can follow this with a final number to list to.
|===

Type the board number you want to edit, then press kbd:[Return].
(Pressing kbd:[Return] by itself exits to the main RELedit menu.)

=== Editing Sub-Board Options

A menu appears with 9 options:


.RELedit sub-board definitions

[%autowidth]
|===
|1 Title |The title of the sub-board.

`---` deletes a Sub when entered as the title, and does not add it if you are adding a sub.

|2 Access |The Access levels that can see this Sub.

Entering kbd:[?] when prompted for the access level calculates access values (refer to #FIXME#).

If the access level is left at 0 when you exit the editor, any other changes are deleted and the board is not added.

|3 SubOp |The handle and ID of the SubOp.
When editing, you can enter the ID number or handle.

|4 Device |The device number where the messages are saved.

|5 Drive |The drive number (for dual drive, Lt. Kernal and other multi-drive devices) where the messages are saved.
(Serial drive owners normally put 0 here.)
The drive number can be 3 digits long to accommodate CMD hard drives.

|6 Status |Toggles between opening and closing the sub-board.
A sub-board can be closed for maintenance if necessary; users do not see the sub-board listed when first entering the sub-system.

|7 Type a| `Std`, `N-An`, etc.
You are presented with Yes and No questions which help select the type of board it will be.
The questions are:

Upload/Download Boards::

Message Bases

#fixme#

|8 Passwd |The password needed to enter the sub-board if the sub-board type requires a password.

|9 Scrns a|
This allows you to edit the entry screens for this Sub:

Any pre-existing screen will be loaded into the editor, and you may use all the usual editing commands.

|===

These 9 options are the same for the U/D and U/X editors as well.
The only difference is the `Type` question which asks `Downloads Only?` and `Free Downloads?` as well as Password.

If the access is 0 or the title is `---`, the data will not be saved (or deleted if editing an existing record).
The BBS also goes through the SIGs (if defined) and removes the board from any SIGs it is on.

=== The SIG Editor

This is much like the Sub, U/D and U/X editors.
The list displays:

* the SIG title
* access
* the SIGop ID
* whether the Subs, U/Ds and U/Xs are open in that SIG

Another new feature found in this version of RELedit (when coupled with the newest version of the TurboRELs) is the ability to "`close`" a section of the board to a SIG.
What this does is prevent the SIG from being listed when the user enters the "`closed`" section.

For example, if you have a SIG that shows the U/X section closed, when a user types kbd:[UX], the SIG will not display, appearing as if the SIG does not exist in that area.

When you type the number of the SIG you wish to edit, the following
options appear:

.RELedit SIG Editing Options
[cols=",",]
|===
| |SIG title.

| |Access levels that can use this SIG.

| |The SIGop for this SIG.
Like SubOp in the Sub, U/D or U/X editors, you can enter either the ID number or handle of the user.

| |Toggles Subs open or closed.

| |Toggles U/Ds open or closed.

| |Toggles U/Xs open or closed.

| |Edit the list of Subs in this SIG.

| |Edit the list of U/Ds in this SIG.

| |Edit the list of U/Xs in this SIG.

| |Edit the entry screens for this SIG (ASCII or C/G).
|===

#FIXME#: fix numbering

==== Editing Lists

Using options 7 through 9, you are presented with a list of the Subs, U/Ds or U/Xs (depending on what option you select) that looks very much like the one users see when listing the available boards in SB/UD/UX.

Everything is keyed off of the position of the board in that list.
For example, if you enter kbd:[D5] it will delete the 5th board in the list of boards for that SIG.

The commands are as follows:

[%autowidth]
[%header]
|===
| Option | Purpose
| kbd:[A]dd board

| Add a board to the end of the list of boards for this SIG.
This command accepts ranges, or type just kbd:[A] and you are asked for the board number (which is the record number you saw in the Sub, U/D and U/X editors).

Typing kbd:[L] at the main `Edit` prompt or the `Add Which` prompt lists the defined Subs/UDs/UXs (depending on which type you are editing).

The Add command also allows multiple adds by giving it a range to add.
For example, kbd:[A5-10] will add Subs 5 to 10.
Range commands also work at the `Add Which` prompt.

| kbd:[I]nsert board

| Identify the number _before_ the board(s) you want inserted. 
Typing kbd:[S] at the edit prompt or the `Insert Before Which` prompt lists the boards in that SIG (again, you can enter a range here as well).
You can give the board number you want the new boards inserted before by typing kbd:[I] followed by the number.

|kbd:[M]ove boards
|You are asked which boards you want to move in the list of boards for that SIG.
Type kbd:[M] and the range at the `Edit` prompt.
Next, you are asked which board you want the selected boards to be moved after.

|kbd:[D]elete boards 
|You are asked which boards you wish to delete.
Again, ranges work here, in the same way.
This _only_ deletes the boards from the SIG list, not from the main Sub/UD/UX lists.
As before, kbd:[L] lists Subs/UDs/UXs, kbd:[S] scans the list of boards selected for that SIG list.
|===

Pressing kbd:[Return] saves the list, returning you to the editing screen for the SIG information.

When you hit kbd:[Return] at the SIG Edit prompt, the data is saved unless the title is `---` or the access is `0`.

If a SIG is deleted, the SIG list for that SIG is also deleted.

=== Netsub Editor

This editor lets you list all of the NetSub IDs you have (you can have up to 60) and edit the lists of boards they are linked to as well as what sub-boards on your BBS are part of that NetSub.

To define a networked sub, first set it up
(refer to <<editing-sub-boards>>).

When you hit N at the main prompt, the BBS looks on your disk for the NetSub data files.  These files are program files that are loaded into memory using one of the new protocol files written for the NetSubs.

====
TIP: If you have a Lt. Kernal, have the Autoload feature turned on, and have a floppy drive with the same device number as the Lt. Kernal, you get a flashing error light on the floppy drive when you enter the NetSub editor as well as every time the new `+.NM.netsub` files are executed during Network Maint.
You might want to remove the floppy drive from your system if this bugs you, but it will not hurt the operation of RELedit or the BBS.
====

The list only displays the NetSub IDs you have defined on your BBS.

Type the number on the left of the NetSub ID you wish to edit and you are taken to the editing screen.

You will now see 18 options:

Option #1 lets you modify the NetSub ID.

Options #2 through #17 are Network IDs of the boards that this NetSub is linked to.  This list should only contain the IDs of boards that you
send NetSubs directly to, not every board that is linked to that NetSub anywhere on the network.

The board IDs are _not_ verified.  This is inline with the new network
design and the reasons for this will be explained when the Image Network is reorganized to make use of the new network features.

Option #18 lets you define which boards on your BBS are parts of this particular NetSub.

The editor that is entered when you select option #18 is very much like the SIG list editor.  (As a matter of fact, both the SIG editor and
NetSub editor use the same routines!)  The only differences are as
follows:

* Up to 60 boards can be defined as being part of a particular NetSub.
* You can only add boards that are not already identified as being Networked.

====
NOTE: To remove Network status from a particular sub-board, it must be deleted and re-added using the Subs editor.
====

* The "Multi-Add" and "Multi-Insert" functions skip not only deleted records, but already networked boards.

While the order of the subs in this list does not in any way affect the order in which they are listed to users, it does affect the order in which they are scanned when `+.NM.netsub` is run.
When a message comes
in to a board, the boards are searched for a post of the same name in the order defined in this section.  If none are found, the boards are scanned in the same order again for a place to post a new message.

You may want to rearrange the order of the Subs to speed up NetSub operation.

====
.Example

If you have a sub containing older posts not responded to as often as a sub found later in the list, you might want to switch their order so the board with more activity comes first.
This way the BBS does not read through older posts for no reason.
====

==== Overflow Subs

This is a system allowing you to set multiple boards as being part of a particular NetSub ID.
When a network message comes in, all subs part of a particular NetSub ID are searched, and the response (or new post) is added where appropriate.

That should just about cover the options available to you in the new RELedit.
I hope you enjoy it and find it useful in maintaining your BBS.
